import { Footer } from '@/components/footer';
import { TopBar } from '@/components/top-bar';
import type { Metadata } from 'next';
import './app.scss';
import './globals.css';
import StyledComponentsRegistry from './registry';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/code-logo.svg' type='image/svg+xml' />
      </head>
      <body className='antialiased dark'>
        <StyledComponentsRegistry>
          <div className='app-container'>
            <TopBar />
            <div className='main-content'>{children}</div>
            <Footer />
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
