services:
  frontend:
    container_name: nextjs-frontend
    # build:
    #   context: ./frontend
    #   dockerfile: ./deploy/Dockerfile
    image: vvasylkovskyi1/vvasylkovskyi-portfolio:latest
    restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
