services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
  #   # image: vvasylkovskyi1/vvasylkovskyi-portfolio:latest
  #   # restart: '${DOCKER_RESTART_POLICY:-unless-stopped}'
    env_file:
      - .env
    ports:
      - '80:80'
    networks:
      - app-network
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  product_app:
    container_name: product_app
    image: vvasylkovskyi1/rpi-product-app:acb03544ca21104f5fe384120503f052c3fcb17d
    # env_file:
    #   - .env
    ports:
      - '3000:3000'
    networks:
      - app-network

  # db:
  #   image: postgres:16
  #   container_name: postgres-db
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: ${DB_DATABASE_NAME}
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - app-network
  #   volumes:
  #     - ./initdb:/docker-entrypoint-initdb.d
      
networks:
  app-network:
    driver: bridge
    name: app-network
