services:
  frontend:
    container_name: nextjs-frontend
    build:
      context: ./frontend
      dockerfile: ./deploy/Dockerfile
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    networks:
      - app-network
  ai-agent:
    container_name: ai-agent
    build:
      context: ./server
      dockerfile: ./deploy/Dockerfile
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    env_file:
      - ./server/.env
    volumes:
      - ./pdfs:/app/pdfs
    ports:
      - "2999:2999"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network
