FROM nginx:alpine

WORKDIR /app
COPY ./ /app
WORKDIR /app

# Config files
COPY nginx.conf /etc/nginx/nginx.conf

# Certificates
COPY certs/vvasylkovskyi_com.pem /etc/ssl/certs/vvasylkovskyi_com.pem
COPY certs/vvasylkovskyi_com.key /etc/ssl/private/vvasylkovskyi_com.key
