name: Migrate & Seed DB

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: "Migrate & Seed DB with notes"
        required: true

jobs:
  migrate-seed:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE_NAME: ${{ secrets.DB_DATABASE_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Run schema.sql
        run: |
          mysql --host="${{ secrets.DB_HOST }}" \
                --user="${{ secrets.DB_USER }}" \
                --password="${{ secrets.DB_PASSWORD }}" \
                --port="${{ secrets.DB_PORT }}" \
                "${{ secrets.DB_DATABASE_NAME }}" < initdb/schema.sql

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run seed script
        run: pnpm run seed-notes
