name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs:
      version:
        description: 'Deploy Blog Server'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Container Image
        id: set_tag
        run: |
          TAG="${{ github.event.inputs.version }}"  # dynamic version input
          echo "Using tag: $TAG"
          docker build -f ./deploy/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG
          echo "::set-output name=image_tag::$TAG"

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          repository: vvasylkovskyi/vvasylkovskyi-infra
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update docker_image_hash in terraform.tfvars
        run: |
          NEW_TAG="${{ needs.build_and_push.outputs.image_tag }}"
          sed -i -E "s|docker_image_hash\s*=\s*\"[^\"]+\"|docker_image_hash = \"$NEW_TAG\"|" terraform.tfvars

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add terraform.tfvars
          git commit -m "Update docker_image_hash to $NEW_TAG"
          git push origin main