name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs:
      version:
        description: 'Deploy Blog Server'
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Container Image
        run: |
          TAG=${{ github.sha }}
          echo "Using tag: $TAG"
          docker build -f ./deploy/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      TAG: ${{ needs.build_and_push.outputs.image_tag }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update docker_image_hash in terraform.tfvars
        working-directory: ./infra/terraform
        run: |
          echo "Using tag: $TAG"
          sed -i -E "s|docker_image_hash\s*=\s*\"[^\"]+\"|docker_image_hash = \"$TAG\"|" terraform.tfvars

      - name: Install Terraform
        working-directory: ./infra/terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infra/terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra/terraform
        run: terraform apply -auto-approve