name: CI

# 1
# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [main]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
      inputs:
      version:
        description: "Deploy Blog Server"
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ github.sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Container Image
        run: |
          TAG=${{ github.sha }}
          echo "Using tag: $TAG"
          docker build -f ./deploy/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG .
          docker push ${{ secrets.DOCKER_USERNAME }}/vvasylkovskyi-portfolio:$TAG

  update_terraform_vars:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      TAG: ${{ needs.build_and_push.outputs.image_tag }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1

    steps:
      - name: Checkout infra repo
        run: |
          git clone https://x-access-token:${{ secrets.INFRA_REPO_PAT }}@github.com/vvasylkovskyi/vvasylkovskyi-infra.git

      - name: Update docker_image_hash_video_service in terraform.tfvars
        run: |
          cd vvasylkovskyi-infra/apps/portfolio
          FILE=terraform.tfvars
          TAG=${{ needs.build_and_push.outputs.image_tag }}
          echo "Replacing docker_image_hash_portfolio_fe with: $TAG"
          sed -i -E "s|(^\s*docker_image_hash_portfolio_fe\s*=\s*\")[^\"]*(\".*)|\1$TAG\2|" $FILE
          echo "--- Resulting terraform.tfvars ---"
          cat $FILE

      - name: Commit and push changes
        run: |
          cd vvasylkovskyi-infra
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add apps/portfolio/terraform.tfvars
            git commit -m "Update docker_image_hash_portfolio_fe to ${{ needs.build_and_push.outputs.image_tag }}"
            git push origin main
          fi
